title: Sara's Portfolio
email: scoggin.dev@gmail.com
description: >-
  Hi, I'm Sara! I'm a Software Engineer who codes by day and writes fiction by night.
  Somewhere between, I daydream into the sky and kick things in Taekwondo.

# For a project site (repo = saracoggin.github.io)
url: "https://s-coggin.github.io"
baseurl: "/saracoggin.github.io"

theme: jekyll-theme-cayman
markdown: kramdown
permalink: /work/:title/
plugins:
  - jekyll-feed

twitter_username: creativelysc
github_username: S-Coggin
